In [ ]:
!git clone https://github.com/Aishwarya-93/Deepfake-Detection-KYC

fatal: destination path 'Deepfake-Detection-KYC' already exists and is not an empty directory.

In [ ]:
%cd Deepfake-Detection-KYC

/content/Deepfake-Detection-KYC

In [ ]:
!pip install -q kaggle

In [ ]:
!kaggle datasets list | head

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                             title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset  FIFA World Cup 2026 Player Performance Dataset         4154062  2026-06-10 12:58:47.093000          10536        251                1
ashyou09/apple-products-pricing-dataset-2020-2026               Apple Products Pricing Dataset (2020-2026)🍎            1569012  2026-07-04 16:06:56.590000           1440         28                1
arjunmehta1992/chocolate-sales-in-20222023                      Chocolate Sales in 2022–2023                           4820417  2026-06-21 03:52:16.600000           3620         48                1
uditjain13/social-media-screen-time-and-mental-health-2026      Social Media, Screen Time & Mental Health 2026          178487  2026-07-05 09:19:11.450000            885         28                1
sunil123kumar/social-media-impact-on-mental-health              Social_Media_Impact_on_Mental Health                     16190  2026-06-10 08:30:07.557000           3909         80                1
mirzayasirabdullah07/netflix-dataset                            Netflix Dataset                                           1949  2026-06-23 11:32:10.120000           1127         30                1
laveshjadon/ai-impact-on-students                               Impact of Ai on Students                               1187170  2026-05-10 23:12:10.070000          22370        503                1

In [ ]:
!kaggle datasets download -d xdxd003/ff-c23

Dataset URL: https://www.kaggle.com/datasets/xdxd003/ff-c23
License(s): other
Downloading ff-c23.zip to /content
100% 16.7G/16.7G [01:59<00:00, 150MB/s]

In [ ]:
!ls -lh

total 17G
drwxr-xr-x 6 root root 4.0K Jul 10 13:45 data
drwxr-xr-x 2 root root 4.0K Jul 10 13:45 docs
-rw-r--r-- 1 root root  206 Jul 10 13:45 environment.yml
-rw-r--r-- 1 root root  17G Dec  7  2024 ff-c23.zip
drwxr-xr-x 6 root root 4.0K Jul 10 13:45 outputs
drwxr-xr-x 2 root root 4.0K Jul 10 13:45 presentations
-rw-r--r-- 1 root root  960 Jul 10 13:45 README.md
drwxr-xr-x 2 root root 4.0K Jul 10 13:45 reports
-rw-r--r-- 1 root root    0 Jul 10 13:45 requirements.txt
drwxr-xr-x 8 root root 4.0K Jul 10 13:45 src

In [ ]:
!pip install -U kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Collecting kaggle
  Downloading kaggle-2.2.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Collecting kagglesdk<1.0,>=0.1.30 (from kaggle)
  Downloading kagglesdk-0.1.33-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Downloading kaggle-2.2.3-py3-none-any.whl (111 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.5/111.5 kB 2.4 MB/s eta 0:00:00
Downloading kagglesdk-0.1.33-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.8/243.8 kB 9.6 MB/s eta 0:00:00
Installing collected packages: kagglesdk, kaggle
  Attempting uninstall: kagglesdk
    Found existing installation: kagglesdk 0.1.23
    Uninstalling kagglesdk-0.1.23:
      Successfully uninstalled kagglesdk-0.1.23
  Attempting uninstall: kaggle
    Found existing installation: kaggle 2.0.2
    Uninstalling kaggle-2.0.2:
      Successfully uninstalled kaggle-2.0.2
Successfully installed kaggle-2.2.3 kagglesdk-0.1.33

In [ ]:
!kaggle --version

Kaggle CLI 2.2.3

In [ ]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   54G   55G  50% /
tmpfs            64M     0   64M   0% /dev
shm             5.7G     0  5.7G   0% /dev/shm
/dev/root       2.0G  1.3G  696M  65% /usr/sbin/docker-init
tmpfs           6.4G  160K  6.4G   1% /var/colab
/dev/sda1       114G   55G   60G  48% /kaggle/input
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware

In [ ]:
!unzip -q ff-c23.zip -d data/raw/

checkdir:  cannot create extraction directory: data/raw
           No such file or directory

In [ ]:
!pwd

/content

In [ ]:
!ls

Deepfake-Detection-KYC	ff-c23.zip  sample_data

In [ ]:
%cd /content/Deepfake-Detection-KYC

/content/Deepfake-Detection-KYC

In [ ]:
!pwd

/content/Deepfake-Detection-KYC

In [ ]:
!ls

data  environment.yml  outputs	      README.md  requirements.txt
docs  ff-c23.zip       presentations  reports	 src

In [ ]:
!mkdir -p data/raw
!mkdir -p data/processed
!mkdir -p data/metadata

In [ ]:
!find data -maxdepth 2 -type d

data
data/processed
data/raw
data/sample
data/metadata

In [ ]:
!unzip -q /content/ff-c23.zip -d data/raw

In [ ]:
!find data/raw -maxdepth 2 -type d

data/raw
data/raw/FaceForensics++_C23
data/raw/FaceForensics++_C23/FaceSwap
data/raw/FaceForensics++_C23/DeepFakeDetection
data/raw/FaceForensics++_C23/csv
data/raw/FaceForensics++_C23/Face2Face
data/raw/FaceForensics++_C23/FaceShifter
data/raw/FaceForensics++_C23/NeuralTextures
data/raw/FaceForensics++_C23/original
data/raw/FaceForensics++_C23/Deepfakes

In [ ]:
from pathlib import Path

# ----------------------------
# Dataset Path
# ----------------------------

DATASET_PATH = Path("data/raw/FaceForensics++_C23")

# ----------------------------
# Check Dataset
# ----------------------------

if not DATASET_PATH.exists():
    print("Dataset not found!")
    exit()

print("=" * 60)
print("FaceForensics++ Dataset Inspection")
print("=" * 60)

print("\nDataset Location:")
print(DATASET_PATH)

print("\nFolders Found:\n")

folders = []

for folder in sorted(DATASET_PATH.iterdir()):

    if folder.is_dir():
      if folder.name != "csv":

        folders.append(folder.name)

        print(f"• {folder.name}")

print("\nTotal folders:", len(folders))

============================================================
FaceForensics++ Dataset Inspection
============================================================

Dataset Location:
data/raw/FaceForensics++_C23

Folders Found:

• DeepFakeDetection
• Deepfakes
• Face2Face
• FaceShifter
• FaceSwap
• NeuralTextures
• original

Total folders: 7

In [ ]:
import os

csv_folder = "data/raw/FaceForensics++_C23/csv"

print("CSV Files:\n")

for file in sorted(os.listdir(csv_folder)):
    print(file)

CSV Files:

DeepFakeDetection.csv
Deepfakes.csv
FF++_Metadata.csv
FF++_Metadata_Shuffled.csv
Face2Face.csv
FaceShifter.csv
FaceSwap.csv
Mean_Data.csv
NeuralTextures.csv
original.csv

In [ ]:
import pandas as pd

df = pd.read_csv(
    "data/raw/FaceForensics++_C23/csv/original.csv"
)

df.head()

,Unnamed: 0,File Path,Label,Frame Count,Width,Height,Codec,File Size(MB)
0,0,original/000.mp4,REAL,396,640,480,h264,0.85
1,1,original/001.mp4,REAL,460,1280,720,h264,2.78
2,2,original/002.mp4,REAL,693,1280,720,h264,2.02
3,3,original/003.mp4,REAL,303,640,480,h264,0.58
4,4,original/004.mp4,REAL,309,1280,720,h264,1.20

In [ ]:
df.columns

Index(['Unnamed: 0', 'File Path', 'Label', 'Frame Count', 'Width', 'Height',
       'Codec', 'File Size(MB)'],
      dtype='object')

In [ ]:
df.sample(5)

,Unnamed: 0,File Path,Label,Frame Count,Width,Height,Codec,File Size(MB)
357,357,original/357.mp4,REAL,346,854,480,h264,0.51
443,443,original/443.mp4,REAL,1146,640,480,h264,1.60
272,272,original/272.mp4,REAL,323,1280,720,h264,1.50
909,909,original/909.mp4,REAL,637,640,480,h264,0.58
595,595,original/595.mp4,REAL,565,1280,720,h264,2.06

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     1000 non-null   int64
 1   File Path      1000 non-null   object
 2   Label          1000 non-null   object
 3   Frame Count    1000 non-null   int64
 4   Width          1000 non-null   int64
 5   Height         1000 non-null   int64
 6   Codec          1000 non-null   object
 7   File Size(MB)  1000 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 62.6+ KB